# Generated by Django 2.1.7 on 2019-03-14 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание партии')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название партии')),
                ('microch', models.CharField(choices=[('MSUE', 'МПГУ'), ('MIPT', 'МФТИ'), ('IRE', 'ИРЭ'), ('OTHER', 'Другое')], default='MSUE', max_length=6, verbose_name='Микроскоп')),
                ('current', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ток, pA')),
                ('voltage', models.CharField(blank=True, max_length=3, null=True, verbose_name='Ускоряющее напряжение, кВ')),
                ('wd', models.CharField(blank=True, max_length=4, null=True, verbose_name='wd, мм')),
                ('ss', models.CharField(blank=True, max_length=3, null=True, verbose_name='Spot Size')),
                ('diaf', models.CharField(blank=True, max_length=1, null=True, verbose_name='Номер диафрагмы')),
                ('hs', models.CharField(blank=True, max_length=3, null=True, verbose_name='hs')),
                ('micro_adv', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
                ('resist', models.CharField(blank=True, max_length=30, null=True, verbose_name='Резист')),
                ('resist_rpm', models.CharField(blank=True, max_length=5, null=True, verbose_name='Скорость нанесения, об/мин')),
                ('resist_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Время нанесения, секунды')),
                ('dry_type', models.CharField(choices=[('HP', 'hot plate'), ('OVEN', 'oven')], default='HP', max_length=6, verbose_name='Тип сушки')),
                ('dry_temp', models.CharField(blank=True, max_length=5, null=True, verbose_name='Температура сушки, °C')),
                ('dry_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Время сушки, секунды')),
                ('dev', models.CharField(blank=True, max_length=10, null=True, verbose_name='Проявитель')),
                ('dev_time', models.CharField(blank=True, max_length=3, null=True, verbose_name='Время проявки, секунды')),
                ('ref', models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], default='YES', max_length=6, verbose_name='Reflow')),
                ('ref_temp', models.CharField(blank=True, max_length=5, null=True, verbose_name='Температура reflow, °C')),
                ('ref_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Время reflow, секунды')),
                ('tr_rec', models.TextField(blank=True, null=True, verbose_name='Травление, рецепт')),
                ('tr_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='Время травления, секунды')),
                ('tr_vel', models.CharField(blank=True, max_length=5, null=True, verbose_name='Скорость травления, нм/с')),
                ('pyth', models.FileField(blank=True, null=True, upload_to='python/%Y/%m/%d', verbose_name='Python файл')),
                ('gds', models.FileField(blank=True, null=True, upload_to='gds/%Y/%m/%d', verbose_name='GDS файл')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Дополнительное поле; изображения, таблицы')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning_logs.Topic'),
        ),
    ]
