# Generated by Django 2.1.7 on 2019-04-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='n',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='n'),
        ),
    ]
