# Generated by Django 2.2.2 on 2019-07-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dose',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Доза, мкКл/см^2'),
        ),
        migrations.AddField(
            model_name='entry',
            name='exp_size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Длина стороны квадрата поля экспонирования, мкм'),
        ),
        migrations.AddField(
            model_name='entry',
            name='exp_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Время экспонирования в точке, мкс'),
        ),
        migrations.AddField(
            model_name='entry',
            name='num_dots',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Количество точек'),
        ),
    ]
