# Generated by Django 2.1.4 on 2019-01-18 16:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
