# Generated by Django 2.1.4 on 2019-01-18 17:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
