# Generated by Django 2.1.4 on 2019-01-18 19:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20190118_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='t1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание партии'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Дополнительное поле; изображения, таблицы'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание партии'),
        ),
    ]
