# Generated by Django 2.1.4 on 2019-01-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20190118_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='t1',
        ),
        migrations.AddField(
            model_name='entry',
            name='dev',
            field=models.TextField(blank=True, null=True, verbose_name='Проявка'),
        ),
        migrations.AddField(
            model_name='entry',
            name='micro',
            field=models.TextField(blank=True, null=True, verbose_name='Микроскоп'),
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название партии'),
        ),
        migrations.AddField(
            model_name='entry',
            name='resist',
            field=models.TextField(blank=True, null=True, verbose_name='Резист'),
        ),
    ]
