# Generated by Django 2.1.4 on 2019-01-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20190118_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ref',
            field=models.TextField(blank=True, null=True, verbose_name='Reflow'),
        ),
    ]
