# Generated by Django 2.2.2 on 2019-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('name1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('name2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество')),
                ('spin', models.CharField(blank=True, max_length=200, null=True, verbose_name='SPIN')),
                ('res_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Researcher ID')),
                ('sc_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Идентификатор учёного в ИС')),
                ('inn', models.CharField(blank=True, max_length=200, null=True, verbose_name='ИНН')),
                ('snils', models.CharField(blank=True, max_length=200, null=True, verbose_name='СНИЛС')),
                ('birthday', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата рождения')),
                ('passport', models.CharField(blank=True, max_length=200, null=True, verbose_name='Паспорт')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tasks', models.ManyToManyField(to='projects.Task')),
            ],
        ),
    ]
