# Generated by Django 2.2.2 on 2019-09-24 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190924_2252'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='owner',
        ),
        migrations.AddField(
            model_name='emp',
            name='task1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='projects.Task'),
            preserve_default=False,
        ),
    ]
