# Generated by Django 2.2.2 on 2019-09-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190924_2256'),
        ('workers', '0002_auto_20190924_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='task1',
        ),
        migrations.AddField(
            model_name='emp',
            name='tasks',
            field=models.ManyToManyField(to='projects.Task'),
        ),
    ]
